/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.swing;

import com.mycompany.pojo.Sepeda;
import com.mycompany.service.SepedaService;
import com.mycompany.serviceImpl.SepedaServiceImpl;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author berka
 */
public class ManageSepeda extends javax.swing.JFrame {
    SepedaService sepedaService;

    /**
     * Creates new form ManageSepeda
     */
    public ManageSepeda() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadData();
    }
    
    public void close() {
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    private void emptyField() {
        txtId.setText("");
        cbJenisSpd.setSelectedIndex(0);
        txtJumlh.setText("");
        txtharga.setText("");
    }
    
    private void loadData() {
        sepedaService = new SepedaServiceImpl();
        List<Sepeda> listSepeda;
        listSepeda = sepedaService.findAll();
        Object[][] objectSepeda = new Object[listSepeda.size()][4];
        
        int counter = 0;
        
        for (Sepeda sepeda : listSepeda) {
            objectSepeda[counter][0] = sepeda.getIdSepeda();
            objectSepeda[counter][1] = sepeda.getJenisSepeda();
            objectSepeda[counter][2] = sepeda.getJumlahSepeda();
            objectSepeda[counter][3] = sepeda.getHargaSewa();
            counter++;
        }
        
        tblSepeda.setModel(new javax.swing.table.DefaultTableModel(
                objectSepeda,
                new String [] {
                    "id_spd", "jenis_spd", "jumlah_sepeda", "harga_sewa"
                }
        ));
    }
    
    private void loadData(Sepeda sepeda) {
        Object[][] objectSepeda = new Object[1][4];
        
        objectSepeda[0][0] = sepeda.getIdSepeda();
        objectSepeda[0][1] = sepeda.getJenisSepeda();
        objectSepeda[0][2] = sepeda.getJumlahSepeda();
        objectSepeda[0][3] = sepeda.getHargaSewa();
        
        tblSepeda.setModel(new javax.swing.table.DefaultTableModel(
                objectSepeda,
                new String [] {
                    "id_spd", "jenis_spd", "jumlah_sepeda", "harga_sewa"
                }
        ));
    }
    
    private Sepeda findSepeda(int id) {
        Sepeda sepeda = new Sepeda();
        sepedaService = new SepedaServiceImpl();
        sepeda = sepedaService.findById(id);
        return sepeda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSepeda = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbJenisSpd = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJumlh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtharga = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 255, 216));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(136, 232, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE SEPEDA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 840, 80);

        tblSepeda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Sepeda", "Jenis Sepeda", "Jumlah Sepeda", "Harga Sewa"
            }
        ));
        tblSepeda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSepedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSepeda);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 390, 210);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setText("Cari berdasarkan");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch);
        txtSearch.setBounds(130, 110, 200, 35);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Jenis Sepeda");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(580, 120, 90, 16);

        cbJenisSpd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbJenisSpd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sendiri", "Bonceng", "Listrik" }));
        jPanel1.add(cbJenisSpd);
        cbJenisSpd.setBounds(580, 150, 200, 35);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Harga Sewa");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(590, 220, 100, 16);

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId);
        txtId.setBounds(440, 150, 100, 35);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 120, 37, 16);

        txtJumlh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlhActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlh);
        txtJumlh.setBounds(440, 250, 100, 35);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah Sepeda");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 220, 100, 16);

        btnRefresh.setBackground(new java.awt.Color(136, 232, 200));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);
        btnRefresh.setBounds(20, 380, 120, 35);

        btnBack.setBackground(new java.awt.Color(136, 232, 200));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(20, 110, 70, 35);

        btnUpdate.setBackground(new java.awt.Color(136, 232, 200));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(650, 320, 120, 35);

        btnDelete.setBackground(new java.awt.Color(136, 232, 200));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(650, 380, 120, 35);

        txtharga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtharga);
        txtharga.setBounds(580, 250, 200, 35);

        btnSave.setBackground(new java.awt.Color(136, 232, 200));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(440, 320, 120, 35);

        btnCari.setBackground(new java.awt.Color(136, 232, 200));
        btnCari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari);
        btnCari.setBounds(340, 110, 70, 35);

        btnClear.setBackground(new java.awt.Color(136, 232, 200));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(440, 380, 120, 35);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 847, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtJumlhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlhActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminDashboard adminDasboard = new AdminDashboard();
        adminDasboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String jenisSepeda;
        int jumlahSepeda, hargaSewa;
        sepedaService = new SepedaServiceImpl();
        
        jenisSepeda = cbJenisSpd.getSelectedItem().toString();
        jumlahSepeda = Integer.parseInt(txtJumlh.getText());
        hargaSewa = Integer.parseInt(txtharga.getText());
        
        Sepeda sepeda = new Sepeda();
        sepeda.setJenisSepeda(jenisSepeda);
        sepeda.setJumlahSepeda(jumlahSepeda);
        sepeda.setHargaSewa(hargaSewa);
        
        sepedaService.create(sepeda);
        JOptionPane.showMessageDialog(null, "Data sepeda berhasil dibuat");
        loadData();
        emptyField();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String jenisSepeda;
        int jumlahSepeda, hargaSewa, idSepeda;
        sepedaService = new SepedaServiceImpl();
        
        idSepeda = Integer.parseInt(txtId.getText());
        jenisSepeda = cbJenisSpd.getSelectedItem().toString();
        jumlahSepeda = Integer.parseInt(txtJumlh.getText());
        hargaSewa = Integer.parseInt(txtharga.getText());
        
        Sepeda sepeda = new Sepeda();
        sepeda.setIdSepeda(idSepeda);
        sepeda.setJenisSepeda(jenisSepeda);
        sepeda.setJumlahSepeda(jumlahSepeda);
        sepeda.setHargaSewa(hargaSewa);
        
        sepedaService.update(sepeda);
        JOptionPane.showMessageDialog(null, "Data sepeda berhasil diupdate");
        loadData();
        emptyField();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblSepedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSepedaMouseClicked
        // TODO add your handling code here:
        String jenisSepeda;
        int jumlahSepeda, hargaSewa, idSepeda;
        
        int row = tblSepeda.getSelectedRow();
        idSepeda = Integer.parseInt(tblSepeda.getValueAt(row, 0).toString());
        jenisSepeda = tblSepeda.getValueAt(row, 1).toString();
        jumlahSepeda = Integer.parseInt(tblSepeda.getValueAt(row, 2).toString());
        hargaSewa = Integer.parseInt(tblSepeda.getValueAt(row, 3).toString());
        
        txtId.setText(idSepeda+"");
        cbJenisSpd.setSelectedItem(jenisSepeda);
        txtJumlh.setText(jumlahSepeda+"");
        txtharga.setText(hargaSewa+"");
    }//GEN-LAST:event_tblSepedaMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int id;
        sepedaService = new SepedaServiceImpl();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        
        id = Integer.parseInt(txtId.getText());
        
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure to delete it?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            sepedaService.delete(id);
            loadData();
            emptyField();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        int id;
        Sepeda searchedSepeda = new Sepeda();
        
        id = Integer.parseInt(txtSearch.getText());
        searchedSepeda = findSepeda(id);
        if (searchedSepeda != null) {
            loadData(searchedSepeda);
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        emptyField();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSepeda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbJenisSpd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSepeda;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJumlh;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtharga;
    // End of variables declaration//GEN-END:variables
}
