/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.swing;

import com.mycompany.pojo.Transaksi;
import com.mycompany.service.TransaksiService;
import com.mycompany.serviceImpl.TransaksiServiceImpl;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author berka
 */
public class ManageTransaksi extends javax.swing.JFrame {
    TransaksiService transaksiService;
    SewaSepeda sewaSepeda = new SewaSepeda();
    private static Transaksi transaksi;

    /**
     * Creates new form ManageTransaksi
     */
    public ManageTransaksi() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadData();
    }
    
    public void close() {
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    private void emptyField() {
        txtOrderid.setText("");
        txtTanggal.setCalendar(null);
        txtJumlahSewa.setText("");
        txtDurasiSewa.setText("");
        txtIdSpd.setText("");
        cbJenisSpd.setSelectedIndex(0);
        txtHargaSewa.setText("");
    }
    
    private void loadData() {
        transaksiService = new TransaksiServiceImpl();
        List<Transaksi> listTransaksi;
        listTransaksi = transaksiService.findAll();
        Object[][] objectTransksi = new Object[listTransaksi.size()][7];
        
        int counter = 0;
        
        for (Transaksi transaksi : listTransaksi) {
            objectTransksi[counter][0] = transaksi.getOrderId();
            objectTransksi[counter][1] = transaksi.getTanggalOrder();
            objectTransksi[counter][2] = transaksi.getJumlahSewa();
            objectTransksi[counter][3] = transaksi.getDurasiSewa();
            objectTransksi[counter][4] = transaksi.getIdSepeda();
            objectTransksi[counter][5] = transaksi.getJenisSpd();
            objectTransksi[counter][6] = transaksi.getHargaSewa();
            counter++;
        }
        
        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
                objectTransksi, 
                new String [] {
                    "order_id", "tgl_order", "jumlah_sewa", "durasi_sewa",
                    "id_spd", "jenis_spd", "harga_sewa"
                }
        ));
    }
    
    private void loadData(Transaksi transaksi) {
        Object[][] objectTransaksi = new Object[1][7];
        
        objectTransaksi[0][0] = transaksi.getOrderId();
        objectTransaksi[0][1] = transaksi.getTanggalOrder();
        objectTransaksi[0][2] = transaksi.getJumlahSewa();
        objectTransaksi[0][3] = transaksi.getDurasiSewa();
        objectTransaksi[0][4] = transaksi.getIdSepeda();
        objectTransaksi[0][5] = transaksi.getJenisSpd();
        objectTransaksi[0][6] = transaksi.getHargaSewa();
           
        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
                objectTransaksi, 
                new String [] {
                    "order_id", "tgl_order", "jumlah_sewa", "durasi_sewa",
                    "id_spd", "jenis_spd", "harga_sewa"
                }
        ));
    }
    
    private Transaksi findTransaksi(int id) {
        Transaksi transaksi = new Transaksi();
        transaksiService = new TransaksiServiceImpl();
        transaksi = transaksiService.findById(id);
        return transaksi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        txtDurasiSewa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtIdSpd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJumlahSewa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHargaSewa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbJenisSpd = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtOrderid = new javax.swing.JTextField();
        btnDelete1 = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 255, 216));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(136, 232, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE TRANSAKSI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 970, 70);

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Tanggal Order", "Jumlah Sewa", "Durasi Sewa", "ID Sepeda", "Jenis Sepeda", "Harga Sewa"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 620, 270);

        txtDurasiSewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDurasiSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasiSewaActionPerformed(evt);
            }
        });
        jPanel1.add(txtDurasiSewa);
        txtDurasiSewa.setBounds(840, 230, 100, 35);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Tanggal Order");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(670, 200, 100, 20);
        jPanel1.add(txtTanggal);
        txtTanggal.setBounds(670, 230, 150, 35);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("ID Sepeda");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(840, 120, 70, 20);

        txtIdSpd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdSpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSpdActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdSpd);
        txtIdSpd.setBounds(840, 150, 100, 35);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Order ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(670, 120, 70, 20);

        txtJumlahSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahSewaActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlahSewa);
        txtJumlahSewa.setBounds(840, 410, 100, 35);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah Sewa");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(840, 380, 90, 20);

        txtHargaSewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHargaSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaSewaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHargaSewa);
        txtHargaSewa.setBounds(670, 410, 140, 35);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Sepeda");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(670, 290, 110, 20);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setText("Cari berdasarkan ID");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch);
        txtSearch.setBounds(350, 110, 200, 35);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Durasi Sewa");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(840, 200, 90, 20);

        cbJenisSpd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbJenisSpd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listrik", "Gowes" }));
        cbJenisSpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisSpdActionPerformed(evt);
            }
        });
        jPanel1.add(cbJenisSpd);
        cbJenisSpd.setBounds(670, 320, 270, 35);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Harga Sewa");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(670, 380, 110, 20);

        btnBack.setBackground(new java.awt.Color(136, 232, 200));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(20, 110, 90, 35);

        txtOrderid.setEditable(false);
        txtOrderid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtOrderid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderidActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrderid);
        txtOrderid.setBounds(670, 150, 100, 35);

        btnDelete1.setBackground(new java.awt.Color(136, 232, 200));
        btnDelete1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete1.setText("DELETE");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete1);
        btnDelete1.setBounds(340, 440, 120, 35);

        btnCari.setBackground(new java.awt.Color(136, 232, 200));
        btnCari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari);
        btnCari.setBounds(560, 110, 80, 35);

        btnRefresh.setBackground(new java.awt.Color(136, 232, 200));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);
        btnRefresh.setBounds(20, 440, 120, 35);

        btnPrint.setBackground(new java.awt.Color(136, 232, 200));
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint);
        btnPrint.setBounds(180, 440, 120, 35);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 978, 546);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDurasiSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasiSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasiSewaActionPerformed

    private void txtIdSpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSpdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSpdActionPerformed

    private void txtJumlahSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahSewaActionPerformed

    private void txtHargaSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaSewaActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminDashboard adminDasboard = new AdminDashboard();
        adminDasboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtOrderidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderidActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int id;
        transaksiService = new TransaksiServiceImpl();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        
        id = Integer.parseInt(txtOrderid.getText());
        
        int dialogResult = JOptionPane.showConfirmDialog (null, "Apakah Anda yakin menghapus data ini?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            transaksiService.delete(id);
            loadData();
            emptyField();
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        int id;
        Transaksi searTransaksi = new Transaksi();
        
        id = Integer.parseInt(txtSearch.getText());
        searTransaksi = findTransaksi(id);
        if (searTransaksi != null) {
            loadData(searTransaksi);
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        String tanggalOrder, jenisSepeda;
        int orderId, jumlahSewa, durasiSewa, idSepeda, hargaSewa;
        Date setTanggalOrder;
        
        int row = tblTransaksi.getSelectedRow();
        orderId = Integer.parseInt(tblTransaksi.getValueAt(row, 0).toString());
        tanggalOrder = tblTransaksi.getValueAt(row, 1).toString();
        jumlahSewa = Integer.parseInt(tblTransaksi.getValueAt(row, 2).toString());
        durasiSewa = Integer.parseInt(tblTransaksi.getValueAt(row, 3).toString());
        idSepeda = Integer.parseInt(tblTransaksi.getValueAt(row, 4).toString());
        jenisSepeda = tblTransaksi.getValueAt(row, 5).toString();
        hargaSewa = Integer.parseInt(tblTransaksi.getValueAt(row, 6).toString());
        
        txtOrderid.setText(orderId+"");
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            setTanggalOrder = dateFormat.parse(tanggalOrder);
            txtTanggal.setDate(setTanggalOrder);
        } catch (ParseException ex) {
            Logger.getLogger(ManageTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtJumlahSewa.setText(jumlahSewa+"");
        txtDurasiSewa.setText(durasiSewa+"");
        txtIdSpd.setText(idSepeda+"");
        cbJenisSpd.setSelectedItem(jenisSepeda);
        txtHargaSewa.setText(hargaSewa+"");
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Daftar Transaksi Rental Sepeda");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        try {
            tblTransaksi.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException e) {
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void cbJenisSpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisSpdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisSpdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbJenisSpd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtDurasiSewa;
    private javax.swing.JTextField txtHargaSewa;
    private javax.swing.JTextField txtIdSpd;
    private javax.swing.JTextField txtJumlahSewa;
    private javax.swing.JTextField txtOrderid;
    private javax.swing.JTextField txtSearch;
    private com.toedter.calendar.JDateChooser txtTanggal;
    // End of variables declaration//GEN-END:variables
}
