/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.swing;

import com.mycompany.pojo.Customer;
import com.mycompany.service.CustomerService;
import com.mycompany.serviceImpl.CustomerServiceImpl;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rifa
 */
public class ManageCustomer extends javax.swing.JFrame {
    CustomerService customerService;

    /**
     * Creates new form ManageCustomer
     */
    public ManageCustomer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void close() {
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    private void emptyField() {
        txtId.setText("");
        txtNik.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtNotelp.setText("");
        bgJenisKelamin.clearSelection();
        txtTanggalLahir.setCalendar(null);
    }
    
    private void loadData() {
        customerService = new CustomerServiceImpl();
        List<Customer> listCustomer;
        listCustomer = customerService.findAll();
        Object[][] objectCustomer = new Object[listCustomer.size()][7];
        
        int counter = 0;
        for (Customer customer : listCustomer) {
            objectCustomer[counter][0] = customer.getIdCustomer();
            objectCustomer[counter][1] = customer.getNik();
            objectCustomer[counter][2] = customer.getNamaCustomer();
            objectCustomer[counter][3] = customer.getTanggalLahir();
            objectCustomer[counter][4] = customer.getJenisKelamin();
            objectCustomer[counter][5] = customer.getNomorTelepon();
            objectCustomer[counter][6] = customer.getAlamat();
            counter++;
        }
        
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
                objectCustomer,
                new String [] {
                    "id_cust", "nik", "nama_cust", "tgl_lhr", "gender", "nomor_telp", "alamat"
                }
        ));
    }
    
    private void loadData(Customer customer) {
        Object[][] objectCustomer = new Object[1][7];
        
        objectCustomer[0][0] = customer.getIdCustomer();
        objectCustomer[0][1] = customer.getNik();
        objectCustomer[0][2] = customer.getNamaCustomer();
        objectCustomer[0][3] = customer.getTanggalLahir();
        objectCustomer[0][4] = customer.getJenisKelamin();
        objectCustomer[0][5] = customer.getNomorTelepon();
        objectCustomer[0][6] = customer.getAlamat();
        
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
                objectCustomer,
                new String [] {
                    "id_cust", "nik", "nama_cust", "tgl_lhr", "gender", "nomor_telp", "alamat"
                }
        ));
    }
    
    private Customer findCustomer(int id) {
        Customer customer = new Customer();
        customerService = new CustomerServiceImpl();
        customer = customerService.findById(id);
        return customer;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNotelp = new javax.swing.JTextField();
        rLakiLaki = new javax.swing.JRadioButton();
        rPerempuan = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtSeacrh = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtTanggalLahir = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 255, 216));
        jPanel1.setLayout(null);

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Customer", "NIK", "Nama Customer", "TTL", "Jenis Kelamin", "No Telp", "Alamat"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(15, 184, 470, 276);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("ID ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 110, 70, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("NIK");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(670, 200, 40, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Nama Customer");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(670, 110, 120, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("TTL");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 200, 40, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(520, 290, 100, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("NoTelp");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(670, 290, 80, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Alamat");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(670, 380, 60, 20);

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtId);
        txtId.setBounds(520, 140, 70, 35);

        txtNik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtNik);
        txtNik.setBounds(670, 230, 200, 35);

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtNama);
        txtNama.setBounds(670, 140, 200, 35);

        txtNotelp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtNotelp);
        txtNotelp.setBounds(670, 320, 200, 35);

        bgJenisKelamin.add(rLakiLaki);
        rLakiLaki.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        rLakiLaki.setText("LAKI LAKI");
        rLakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLakiLakiActionPerformed(evt);
            }
        });
        jPanel1.add(rLakiLaki);
        rLakiLaki.setBounds(520, 330, 90, 25);

        bgJenisKelamin.add(rPerempuan);
        rPerempuan.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        rPerempuan.setText("PEREMPUAN");
        rPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPerempuanActionPerformed(evt);
            }
        });
        jPanel1.add(rPerempuan);
        rPerempuan.setBounds(520, 370, 110, 25);

        btnBack.setBackground(new java.awt.Color(136, 232, 200));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(20, 140, 80, 35);

        btnSearch.setBackground(new java.awt.Color(136, 232, 200));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("CARI");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);
        btnSearch.setBounds(380, 140, 100, 35);

        btnRefresh.setBackground(new java.awt.Color(136, 232, 200));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);
        btnRefresh.setBounds(20, 480, 120, 35);

        txtSeacrh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSeacrh.setText("Cari Berdasarkan");
        jPanel1.add(txtSeacrh);
        txtSeacrh.setBounds(170, 140, 200, 35);

        btnDelete.setBackground(new java.awt.Color(136, 232, 200));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(520, 480, 120, 35);

        btnClear.setBackground(new java.awt.Color(136, 232, 200));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(520, 420, 120, 35);
        jPanel1.add(txtTanggalLahir);
        txtTanggalLahir.setBounds(520, 230, 120, 35);

        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(670, 410, 200, 100);

        jPanel2.setBackground(new java.awt.Color(136, 232, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE CUSTOMER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 80);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(909, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rLakiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLakiLakiActionPerformed
        // TODO add your handling code here:
        gender = "Laki - Laki";
    }//GEN-LAST:event_rLakiLakiActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        int id;
        Customer searchedCustomer = new Customer();
        
        id = Integer.parseInt(txtSeacrh.getText());
        searchedCustomer = findCustomer(id);
        if (searchedCustomer != null) {
            loadData(searchedCustomer);
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminDashboard adminDasboard = new AdminDashboard();
        adminDasboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        // TODO add your handling code here:
        String nik, namaCustomer, tanggalLahir, gender, nomorTelp, alamat;
        int id;
        Date setTanggalLahir;
        
        int row = tblCustomer.getSelectedRow();
        id = Integer.parseInt(tblCustomer.getValueAt(row, 0).toString());
        nik = tblCustomer.getValueAt(row, 1).toString();
        namaCustomer = tblCustomer.getValueAt(row, 2).toString();
        tanggalLahir = tblCustomer.getValueAt(row, 3).toString();
        gender = tblCustomer.getValueAt(row, 4).toString();
        nomorTelp = tblCustomer.getValueAt(row, 5).toString();
        alamat = tblCustomer.getValueAt(row, 6).toString();
        
        txtId.setText(id+"");
        txtNik.setText(nik);
        txtNama.setText(namaCustomer);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            setTanggalLahir = dateFormat.parse(tanggalLahir);
            txtTanggalLahir.setDate(setTanggalLahir);
        } catch (ParseException ex) {
            Logger.getLogger(ManageTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (gender.equals("Laki Laki")) {
            rLakiLaki.setSelected(true);
        }
        if (gender.equals("Perempuan")) {
            rPerempuan.setSelected(true);
        }
        txtNotelp.setText(nomorTelp);
        txtAlamat.setText(alamat);
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        emptyField();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int id;
        customerService = new CustomerServiceImpl();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        
        id = Integer.parseInt(txtId.getText());
        
        int dialogResult = JOptionPane.showConfirmDialog (null, "Apakah Anda yakin untuk menghapus data ini?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            customerService.delete(id);
            loadData();
            emptyField();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void rPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPerempuanActionPerformed
        // TODO add your handling code here:
        gender = "Perempuan";
    }//GEN-LAST:event_rPerempuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJenisKelamin;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rLakiLaki;
    private javax.swing.JRadioButton rPerempuan;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNotelp;
    private javax.swing.JTextField txtSeacrh;
    private com.toedter.calendar.JDateChooser txtTanggalLahir;
    // End of variables declaration//GEN-END:variables
    private String gender;
}
