/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.swing;

import com.mycompany.pojo.Customer;
import com.mycompany.pojo.Sepeda;
import com.mycompany.pojo.Transaksi;
import com.mycompany.service.SepedaService;
import com.mycompany.service.TransaksiService;
import com.mycompany.serviceImpl.SepedaServiceImpl;
import com.mycompany.serviceImpl.TransaksiServiceImpl;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author berka
 */
public class SewaSepeda extends javax.swing.JFrame {
    SepedaService sepedaService;
    TransaksiService transaksiService;
    private static Customer customer;
    
    /**
     * Creates new form SewaSepeda
     */
    public SewaSepeda() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public void close() {
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    private void emptyField() {
        txtIdSpd.setText("");
        cbJenisSpd.setSelectedIndex(0);
        txtJumlahSpd.setText("");
        txtHargaSewa.setText("");
        txtTanggal.setCalendar(null);
        txtDurasi.setText("");
        txtTotalHarga.setText("");
        txtJumlahSewa.setText("");
        txtSearch.setText("");
    }
    
    private void loadData() {
        sepedaService = new SepedaServiceImpl();
        List<Sepeda> listSepeda;
        listSepeda = sepedaService.findAll();
        Object[][] objectSepeda = new Object[listSepeda.size()][4];
        
        int counter = 0;
        
        for (Sepeda sepeda : listSepeda) {
            objectSepeda[counter][0] = sepeda.getIdSepeda();
            objectSepeda[counter][1] = sepeda.getJenisSepeda();
            objectSepeda[counter][2] = sepeda.getJumlahSepeda();
            objectSepeda[counter][3] = sepeda.getHargaSewa();
            counter++;
        }
        
        tblSepeda.setModel(new javax.swing.table.DefaultTableModel(
                objectSepeda,
                new String [] {
                    "id_spd", "jenis_spd", "jumlah_sepeda", "harga_sewa"
                }
        ));
    }
    
    private void loadData(Sepeda sepeda) {
        Object[][] objectSepeda = new Object[1][4];
        
        objectSepeda[0][0] = sepeda.getIdSepeda();
        objectSepeda[0][1] = sepeda.getJenisSepeda();
        objectSepeda[0][2] = sepeda.getJumlahSepeda();
        objectSepeda[0][3] = sepeda.getHargaSewa();
        
        tblSepeda.setModel(new javax.swing.table.DefaultTableModel(
                objectSepeda,
                new String [] {
                    "id_spd", "jenis_spd", "jumlah_sepeda", "harga_sewa"
                }
        ));
    }
    
    private Sepeda findSepeda(int id) {
        Sepeda sepeda = new Sepeda();
        sepedaService = new SepedaServiceImpl();
        sepeda = sepedaService.findById(id);
        return sepeda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSepeda = new javax.swing.JTable();
        txtHargaSewa = new javax.swing.JButton();
        txtIdSpd = new javax.swing.JButton();
        cbJenisSpd = new javax.swing.JComboBox<>();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtJumlahSpd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnPilihSpd = new javax.swing.JButton();
        btnSewaSpd = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtTotalHarga = new javax.swing.JTextField();
        txtJumlahSewa = new javax.swing.JTextField();
        txtDurasi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 255, 216));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(136, 232, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEWA SEPEDA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 840, 70);

        tblSepeda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID SEPEDA", "JENIS SEPEDA", "JUMLAH SEPEDA", "HARGA SEWA"
            }
        ));
        tblSepeda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSepedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSepeda);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 410, 340);

        txtHargaSewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHargaSewa.setEnabled(false);
        txtHargaSewa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txtHargaSewa);
        txtHargaSewa.setBounds(460, 300, 200, 35);

        txtIdSpd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdSpd.setEnabled(false);
        jPanel1.add(txtIdSpd);
        txtIdSpd.setBounds(690, 140, 120, 35);

        cbJenisSpd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbJenisSpd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sendiri", "Bonceng", "Listrik" }));
        cbJenisSpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisSpdActionPerformed(evt);
            }
        });
        jPanel1.add(cbJenisSpd);
        cbJenisSpd.setBounds(460, 220, 200, 35);
        jPanel1.add(txtTanggal);
        txtTanggal.setBounds(460, 140, 200, 35);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Jumlah Sewa");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(690, 360, 100, 19);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Tanggal Pemesanan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(460, 110, 150, 19);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("ID Sepeda");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(690, 110, 70, 19);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Sepeda");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(460, 190, 100, 19);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah Sepeda");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(690, 190, 100, 19);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Harga Sewa");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(460, 270, 100, 19);

        txtJumlahSpd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJumlahSpd.setEnabled(false);
        txtJumlahSpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahSpdActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlahSpd);
        txtJumlahSpd.setBounds(690, 220, 120, 35);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Durasi Sewa");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(690, 270, 100, 19);

        btnPilihSpd.setBackground(new java.awt.Color(136, 232, 200));
        btnPilihSpd.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnPilihSpd.setText("PILIH SEPEDA");
        btnPilihSpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihSpdActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilihSpd);
        btnPilihSpd.setBounds(460, 450, 150, 35);

        btnSewaSpd.setBackground(new java.awt.Color(136, 232, 200));
        btnSewaSpd.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSewaSpd.setText("SEWA SEPEDA");
        btnSewaSpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSewaSpdActionPerformed(evt);
            }
        });
        jPanel1.add(btnSewaSpd);
        btnSewaSpd.setBounds(660, 450, 150, 35);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setText("Cari berdasarkan");
        jPanel1.add(txtSearch);
        txtSearch.setBounds(120, 110, 230, 35);

        btnSearch.setBackground(new java.awt.Color(136, 232, 200));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("CARI");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);
        btnSearch.setBounds(360, 110, 70, 35);

        btnRefresh.setBackground(new java.awt.Color(136, 232, 200));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);
        btnRefresh.setBounds(190, 510, 120, 35);

        btnBack.setBackground(new java.awt.Color(136, 232, 200));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(20, 110, 72, 35);

        btnCancel.setBackground(new java.awt.Color(136, 232, 200));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);
        btnCancel.setBounds(20, 510, 120, 35);

        txtTotalHarga.setEditable(false);
        jPanel1.add(txtTotalHarga);
        txtTotalHarga.setBounds(460, 380, 200, 40);
        jPanel1.add(txtJumlahSewa);
        txtJumlahSewa.setBounds(690, 380, 100, 40);

        txtDurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasiActionPerformed(evt);
            }
        });
        jPanel1.add(txtDurasi);
        txtDurasi.setBounds(690, 300, 90, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("menit");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(790, 306, 43, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setText("Total Harga");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(460, 360, 100, 19);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(854, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbJenisSpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisSpdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisSpdActionPerformed

    private void txtJumlahSpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahSpdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahSpdActionPerformed

    private void btnPilihSpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihSpdActionPerformed
        // TODO add your handling code here:
        String jenisSepeda;
        int jumlahSepeda, hargaSewa;
        sepedaService = new SepedaServiceImpl();
        
        jenisSepeda = cbJenisSpd.getSelectedItem().toString();
        jumlahSepeda = Integer.parseInt(txtJumlahSpd.getText());
        hargaSewa = Integer.parseInt(txtHargaSewa.getText());
        
        Sepeda sepeda = new Sepeda();
        sepeda.setJenisSepeda(jenisSepeda);
        sepeda.setJumlahSepeda(jumlahSepeda);
        sepeda.setHargaSewa(hargaSewa);
        
        String tanggalOrder;
        int durasiSewa, jumlahSewa;
        Date date = txtTanggal.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        tanggalOrder = dateFormat.format(date);
        durasiSewa = Integer.parseInt(txtDurasi.getText());
        jumlahSewa = Integer.parseInt(txtJumlahSewa.getText());
        
        Transaksi transaksi = new Transaksi();
        transaksi.setTanggalOrder(tanggalOrder);
        transaksi.setDurasiSewa(durasiSewa);
        transaksi.setJumlahSewa(jumlahSewa);
        
        int totalHarga;
        if (durasiSewa >= 60) {
        totalHarga = hargaSewa * (durasiSewa / 60) * jumlahSewa;
        } else {
        totalHarga = (hargaSewa * jumlahSewa);
        }
        String byr = Integer.toString(totalHarga);
        txtTotalHarga.setText(byr);
    }//GEN-LAST:event_btnPilihSpdActionPerformed

    private void tblSepedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSepedaMouseClicked
        // TODO add your handling code here:
        String jenisSepeda;
        int jumlahSepeda, hargaSewa, idSepeda;
        
        int row = tblSepeda.getSelectedRow();
        idSepeda = Integer.parseInt(tblSepeda.getValueAt(row, 0).toString());
        jenisSepeda = tblSepeda.getValueAt(row, 1).toString();
        jumlahSepeda = Integer.parseInt(tblSepeda.getValueAt(row, 2).toString());
        hargaSewa = Integer.parseInt(tblSepeda.getValueAt(row, 3).toString());
        
        txtIdSpd.setText(idSepeda+"");
        cbJenisSpd.setSelectedItem(jenisSepeda);
        txtJumlahSpd.setText(jumlahSepeda+"");
        txtHargaSewa.setText(hargaSewa+"");
        
    }//GEN-LAST:event_tblSepedaMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CustomerDashboard customerDashboard = new CustomerDashboard();
        customerDashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSewaSpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSewaSpdActionPerformed
        // TODO add your handling code here:
        String jenisSepeda;
        int jumlahSepeda, hargaSewa, idSepeda, durasiSewa, jumlahSewa, sisaJumlahSepeda;
        String tanggalOrder;
        transaksiService = new TransaksiServiceImpl();
      
        Date date = txtTanggal.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        tanggalOrder = dateFormat.format(date);
        jumlahSewa = Integer.parseInt(txtJumlahSewa.getText());
        durasiSewa = Integer.parseInt(txtDurasi.getText());
        idSepeda = Integer.parseInt(txtIdSpd.getText());
        jenisSepeda = cbJenisSpd.getSelectedItem().toString();
        hargaSewa = Integer.parseInt(txtHargaSewa.getText());
        jumlahSepeda = Integer.parseInt(txtJumlahSpd.getText());
        sisaJumlahSepeda = (jumlahSepeda - jumlahSewa);
        
        Transaksi transaksi = new Transaksi();
        transaksi.setTanggalOrder(tanggalOrder);
        transaksi.setJumlahSewa(jumlahSewa);
        transaksi.setDurasiSewa(durasiSewa);
        transaksi.setIdSepeda(idSepeda);
        transaksi.setJenisSpd(jenisSepeda);
        transaksi.setHargaSewa(hargaSewa);
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Anda yakin untuk melakukan Transaksi?", "Warning", dialogButton);

        if (dialogResult == JOptionPane.YES_OPTION) {
            transaksiService.create(transaksi);
            JOptionPane.showMessageDialog(null, "Data transaksi berhasil ditambahkan!");
            loadData();
            emptyField();
        }
    }//GEN-LAST:event_btnSewaSpdActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        emptyField();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasiActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        int id;
        Sepeda searchedSepeda = new Sepeda();
        
        id = Integer.parseInt(txtSearch.getText());
        searchedSepeda = findSepeda(id);
        if (searchedSepeda != null) {
            loadData(searchedSepeda);
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SewaSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SewaSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SewaSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SewaSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SewaSepeda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPilihSpd;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSewaSpd;
    private javax.swing.JComboBox<String> cbJenisSpd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSepeda;
    private javax.swing.JTextField txtDurasi;
    private javax.swing.JButton txtHargaSewa;
    private javax.swing.JButton txtIdSpd;
    private javax.swing.JTextField txtJumlahSewa;
    private javax.swing.JButton txtJumlahSpd;
    private javax.swing.JTextField txtSearch;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
